name: Lizard Runner
on:
  pull_request:
    types:
      - synchronize
      - labeled
      - assigned
      - opened
    paths:
      - "src/**"
      - "app/**"
      - "__tests__/**"
    branches:
      - main
      - production
      - staging
      - sandbox
      - develop
      - sp*
      - feature/*
jobs:
  lizard:
    if: >
      github.event.pull_request.assignee != null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
        with:
          ignore_warnings: "2"
          CCN: "20"
          path: "./src ./jevic"
          length: "10000"
          exclude: "./src/test/*"
