name: reviewdog
on:
  pull_request:
    types:
      - synchronize
      - labeled
      - assigned
      - opened
    paths:
      - "src/**"
      - "app/**"
      - "__tests__/**"
    branches:
      - main
      - production
      - staging
      - sandbox
      - develop
      - sp*
      - feature/*

jobs:
  eslint:
    if: >
      github.event.pull_request.assignee != null
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          node_options: "--max_old_space_size=8192"
          reporter: github-pr-review
          workdir: "./"
          eslint_flags: "--no-eslintrc -c .eslintrc.json src/"
  misspell:
    if: >
      github.event.pull_request.assignee != null
    name: runner / misspell
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          locale: "US"
